[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DQBIT_BUTTON_PIN=1
    -DQBIT_BUTTON_ACTIVE_LOW=1
    -DQBIT_I2C_SDA_PIN=20
    -DQBIT_I2C_SCL_PIN=21
lib_deps =
    olikraus/U8g2@^2.36.18
